name: continuous (Preview) releases
# avoids paths like tests folder, .md, and anything that starts with `.`
# also avoids tags.
on:
  workflow_dispatch: 
  pull_request_review:
    types: [submitted]
  pull_request: 
    types: [labeled, synchronize]
    paths: 
      - 'build/**'
      - '!tests/**'
      - '!*.md'
      - '!.*'
  push: 
    paths:
    - 'build/**'
    - '!tests/**'
    - '!*.md'
    - '!.*'
    branches: [main]
    tags:
      - "!**"

permissions: 
  pull-requests: write


jobs:
  approved:
    # ignore for now!  
    # if: github.event.review.state == 'APPROVED' && !contains(github.event.pull_request.labels.*.name, 'DO NOT PREVIEW RELEASE') || contains(github.event.pull_request.labels.*.name, 'Bypass check - PREVIEW RELEASE') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'PR Manual CI RUN')) 
    #     || contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) 
    if: contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install pkg-pr-new & prebuild, dependencies
        run: npm install pkg-pr-new --save-dev --no-frozen-lockfile

      - run: npx pkg-pr-new publish

      #   ignore for now 
      # - name: Remove Manual PR Run label
      #   if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'PR Manual CI RUN')
      #   run: gh pr edit $PR --remove-label "$labels"
      #   env:
      #     PR: ${{ github.event.pull_request.number }}
      #     labels: 'PR Manual CI RUN'
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}